# Generated by Django 5.0 on 2023-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.IntegerField(blank=True),
        ),
    ]
