# Generated by Django 5.0 on 2024-01-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
