# Generated by Django 5.0 on 2023-12-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0006_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('poster', models.ImageField(help_text='An image representing the course', upload_to='course_posters/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='Account.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Account.teacher')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
