# Generated by Django 5.0 on 2023-12-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(help_text='An image representing the course', upload_to='Learning/course_posters/'),
        ),
    ]
