# Generated by Django 5.0 on 2024-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0003_assessment_created_assessment_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, to='Learning.choice'),
        ),
    ]
