# Generated by Django 5.0 on 2024-01-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0008_file_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='learning/course/photos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Learning.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='learning/course/videos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Learning.course')),
            ],
        ),
    ]
