# Generated by Django 5.0 on 2024-01-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0009_coursephoto_coursevideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Quiz',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='assessment',
            new_name='quiz',
        ),
    ]
