# Generated by Django 4.2.13 on 2024-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0011_remove_coursephoto_course_remove_coursevideo_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='content',
            field=models.TextField(),
        ),
    ]
