# Generated by Django 4.2.13 on 2024-06-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0012_alter_reading_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
