# Generated by Django 4.2.13 on 2024-06-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Learning', '0013_course_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsectionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='Learning.subsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subsection')},
            },
        ),
    ]
