# Generated by Django 4.2.13 on 2024-06-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning', '0016_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Learning.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='Choicee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Learning.questionn')),
            ],
        ),
    ]
