# Generated by Django 5.0 on 2024-01-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Social.photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Social.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=None, upload_to='Social/videos/'),
        ),
    ]
