# Generated by Django 5.0 on 2024-01-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_alter_post_photos_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Social.photo'),
        ),
    ]
