# Generated by Django 5.0 on 2024-01-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_alter_post_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='Social/videos/'),
        ),
    ]
