# Generated by Django 5.0 on 2024-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='social/post/photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='social/post/videos/'),
        ),
    ]
