# Generated by Django 5.0.3 on 2024-03-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
