# Generated by Django 5.0.3 on 2024-03-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0010_share'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
    ]
